CREATE ROLE REPLICATION_TARGET_USER NOT IDENTIFIED;
GRANT CREATE SESSION TO REPLICATION_TARGET_USER;

GRANT ALTER ANY PROCEDURE TO REPLICATION_TARGET_USER;
GRANT ALTER ANY SEQUENCE TO REPLICATION_TARGET_USER;
GRANT ALTER ANY TABLE TO REPLICATION_TARGET_USER;
GRANT CREATE ANY INDEX TO REPLICATION_TARGET_USER;
GRANT CREATE ANY PROCEDURE TO REPLICATION_TARGET_USER;
GRANT CREATE ANY SEQUENCE TO REPLICATION_TARGET_USER;
GRANT CREATE ANY TABLE TO REPLICATION_TARGET_USER;
GRANT CREATE ANY VIEW TO REPLICATION_TARGET_USER;
GRANT DELETE ANY TABLE TO REPLICATION_TARGET_USER;
GRANT DROP ANY INDEX TO REPLICATION_TARGET_USER;
GRANT DROP ANY PROCEDURE TO REPLICATION_TARGET_USER;
GRANT DROP ANY SEQUENCE TO REPLICATION_TARGET_USER;
GRANT DROP ANY TABLE TO REPLICATION_TARGET_USER;
GRANT DROP ANY VIEW TO REPLICATION_TARGET_USER;
GRANT INSERT ANY TABLE TO REPLICATION_TARGET_USER;
GRANT LOCK ANY TABLE TO REPLICATION_TARGET_USER;
GRANT SELECT ANY TABLE TO REPLICATION_TARGET_USER;
GRANT SELECT ANY TRANSACTION TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_INDEXES TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_OBJECTS TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_SEQUENCES TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_SYNONYMS TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_TAB_PRIVS TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_TABLES TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_TRIGGERS TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_TYPES TO REPLICATION_TARGET_USER;
GRANT SELECT ON DBA_USERS TO REPLICATION_TARGET_USER;
GRANT SELECT ON V$NLS_PARAMETERS TO REPLICATION_TARGET_USER;
GRANT SELECT ON V$TIMEZONE_NAMES TO REPLICATION_TARGET_USER;
GRANT UPDATE ANY TABLE TO REPLICATION_TARGET_USER;

EXEC RDSADMIN.RDSADMIN_UTIL.SET_CONFIGURATION('ARCHIVELOG RETENTION HOURS',48);

CREATE USER "&1" IDENTIFIED BY "&2"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE APP_PROFILE
    ACCOUNT UNLOCK;

ALTER USER "&1" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO "&1";
GRANT REPLICATION_TARGET_USER TO "&1";
