CREATE USER CP_ASA IDENTIFIED BY "&1"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE USER_PROFILE
    ACCOUNT UNLOCK;

GRANT BIP_PRODOPS_READONLY_ROLE TO CP_ASA;
ALTER USER CP_ASA DEFAULT ROLE ALL;

COMMIT;