CREATE BIGFILE TABLESPACE "&3" DATAFILE SIZE 128M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
    LOGGING
    ONLINE
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    BLOCKSIZE 8 K
    SEGMENT SPACE MANAGEMENT AUTO
    FLASHBACK ON;

CREATE USER "&1" IDENTIFIED BY "&2"
    DEFAULT TABLESPACE "&3"
    TEMPORARY TABLESPACE TEMP
    PROFILE APP_PROFILE
    ACCOUNT UNLOCK;

ALTER USER "&1" QUOTA UNLIMITED ON "&3";
GRANT CREATE SESSION TO "&1";
GRANT RESOURCE TO "&1";
