--CREATE PASSWORD VERIFY FUNCTION
BEGIN
    RDSADMIN.RDSADMIN_PASSWORD_VERIFY.CREATE_VERIFY_FUNCTION (
        P_VERIFY_FUNCTION_NAME      => 'BIP_VERIFY_STRONG_PASSWORD', 
        P_MIN_LENGTH                => 16, 
        P_MAX_LENGTH                => 64,
        P_MIN_LETTERS               => 4,
        P_MIN_UPPERCASE             => 1,
        P_MIN_LOWERCASE             => 1,
        P_MIN_DIGITS                => 1, 
        P_MIN_SPECIAL               => 1,
        P_MIN_DIFFERENT_CHARS       => 4,
        P_DISALLOW_USERNAME         => TRUE,
        P_DISALLOW_SIMPLE_STRINGS   => TRUE,
        P_DISALLOW_AT_SIGN          => TRUE );
END;
/

--CREATE PROFILES
CREATE PROFILE APP_PROFILE LIMIT
    SESSIONS_PER_USER UNLIMITED
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PRIVATE_SGA UNLIMITED
    FAILED_LOGIN_ATTEMPTS 1
    PASSWORD_LIFE_TIME 365
    PASSWORD_REUSE_TIME DEFAULT
    PASSWORD_REUSE_MAX 25
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME 3
    PASSWORD_VERIFY_FUNCTION BIP_VERIFY_STRONG_PASSWORD;

CREATE PROFILE DBA_PROFILE LIMIT
    SESSIONS_PER_USER 40
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PRIVATE_SGA UNLIMITED
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_TIME DEFAULT
    PASSWORD_REUSE_MAX 25
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME 3
    PASSWORD_VERIFY_FUNCTION BIP_VERIFY_STRONG_PASSWORD;

CREATE PROFILE USER_PROFILE LIMIT
    SESSIONS_PER_USER 40
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    CONNECT_TIME UNLIMITED
    IDLE_TIME 15
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PRIVATE_SGA UNLIMITED
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_TIME DEFAULT
    PASSWORD_REUSE_MAX 25
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME 3
    PASSWORD_VERIFY_FUNCTION BIP_VERIFY_STRONG_PASSWORD;

CREATE PROFILE ADMIN_PROFILE LIMIT
    SESSIONS_PER_USER 40
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL UNLIMITED
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PRIVATE_SGA UNLIMITED
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_REUSE_TIME DEFAULT
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME UNLIMITED
    PASSWORD_VERIFY_FUNCTION DEFAULT;

--MOVE DEFAULT ORACLE ACCOUNTS TO APP_PROFILE;
ALTER USER ANONYMOUS PROFILE APP_PROFILE;
ALTER USER APPQOSSYS PROFILE APP_PROFILE;
--ALTER USER AUDSYS PROFILE APP_PROFILE;
ALTER USER CTXSYS PROFILE APP_PROFILE;
ALTER USER DBADMIN PROFILE ADMIN_PROFILE;
ALTER USER DBSFWUSER PROFILE APP_PROFILE;
ALTER USER DBSNMP PROFILE APP_PROFILE;
ALTER USER DIP PROFILE APP_PROFILE;
ALTER USER GGSYS PROFILE APP_PROFILE;
ALTER USER GSMADMIN_INTERNAL PROFILE APP_PROFILE;
ALTER USER GSMCATUSER PROFILE APP_PROFILE;
ALTER USER GSMUSER PROFILE APP_PROFILE;
ALTER USER OUTLN PROFILE APP_PROFILE;
ALTER USER REMOTE_SCHEDULER_AGENT PROFILE APP_PROFILE;
ALTER USER SYS$UMF PROFILE APP_PROFILE;
ALTER USER SYSBACKUP PROFILE APP_PROFILE;
ALTER USER SYSDG PROFILE APP_PROFILE;
ALTER USER SYSKM PROFILE APP_PROFILE;
ALTER USER SYSRAC PROFILE APP_PROFILE;
--ALTER USER XDB PROFILE APP_PROFILE;

--CREATE BIP_DBA USER FOR OPERATIONS
CREATE BIGFILE TABLESPACE BIP_DBA_DATA DATAFILE SIZE 128M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
    LOGGING
    ONLINE
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    BLOCKSIZE 8 K
    SEGMENT SPACE MANAGEMENT AUTO
    FLASHBACK ON;

CREATE USER BIP_DBA IDENTIFIED BY "&1"
    DEFAULT TABLESPACE BIP_DBA_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE DBA_PROFILE
    ACCOUNT UNLOCK;

GRANT DBA TO BIP_DBA;
--extra command to set profile in the case that user exists
ALTER USER BIP_DBA PROFILE DBA_PROFILE;

--MODIFY DBSNMP
ALTER USER DBSNMP IDENTIFIED BY "&2";
ALTER USER DBSNMP ACCOUNT UNLOCK;

--CREATE BIP_READONLY_ROLE
CREATE ROLE BIP_PRODOPS_READONLY_ROLE NOT IDENTIFIED;
GRANT CONNECT TO BIP_PRODOPS_READONLY_ROLE;

-- LIQUIBASE_ADMIN
-- Sourced from https://datical-cs.atlassian.net/wiki/spaces/DDOC/pages/896567868/Multi-Schema+Projects+-+Oracle+on+Amazon+RDS+Roles+and+Permissions
CREATE ROLE LIQUIBASE_ADMIN_ROLE NOT IDENTIFIED;
 
GRANT ADMINISTER DATABASE TRIGGER TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY INDEX TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY MATERIALIZED VIEW TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY PROCEDURE TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY SEQUENCE TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY TRIGGER TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER ANY TYPE TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER SESSION TO LIQUIBASE_ADMIN_ROLE;
GRANT ALTER USER TO LIQUIBASE_ADMIN_ROLE;
GRANT COMMENT ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY EDITION TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY INDEX TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY MATERIALIZED VIEW TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY PROCEDURE TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY SEQUENCE TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY SYNONYM TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY TRIGGER TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY TYPE TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ANY VIEW TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE PUBLIC SYNONYM TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE ROLE TO LIQUIBASE_ADMIN_ROLE;
GRANT CREATE SESSION TO LIQUIBASE_ADMIN_ROLE;
GRANT DELETE ANY TABLE TO LIQUIBASE_ADMIN_ROLE WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY INDEX TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY MATERIALIZED VIEW TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY PROCEDURE TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY SEQUENCE TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY SYNONYM TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY TRIGGER TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY TYPE TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP ANY VIEW TO LIQUIBASE_ADMIN_ROLE;
GRANT DROP PUBLIC SYNONYM TO LIQUIBASE_ADMIN_ROLE;
GRANT EXECUTE ANY PROCEDURE TO LIQUIBASE_ADMIN_ROLE;
GRANT GRANT ANY OBJECT PRIVILEGE TO LIQUIBASE_ADMIN_ROLE;
GRANT INSERT ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
GRANT SELECT ANY DICTIONARY TO LIQUIBASE_ADMIN_ROLE;
GRANT SELECT ANY SEQUENCE TO LIQUIBASE_ADMIN_ROLE;
GRANT SELECT ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
GRANT SELECT_CATALOG_ROLE TO LIQUIBASE_ADMIN_ROLE;
GRANT UPDATE ANY TABLE TO LIQUIBASE_ADMIN_ROLE;
 
begin
    rdsadmin.rdsadmin_util.grant_sys_object(
        p_obj_name  => 'DBMS_METADATA',
        p_grantee   => 'LIQUIBASE_ADMIN_ROLE',
        p_privilege => 'EXECUTE');
end;
/
begin
    rdsadmin.rdsadmin_util.grant_sys_object(
        p_obj_name  => 'UTL_FILE',
        p_grantee   => 'LIQUIBASE_ADMIN_ROLE',
        p_privilege => 'EXECUTE');
end;
/

--CREATE LIQUIBASE_ADMIN
CREATE USER LIQUIBASE_ADMIN IDENTIFIED BY "&3"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE APP_PROFILE
  ACCOUNT UNLOCK;

GRANT LIQUIBASE_ADMIN_ROLE TO LIQUIBASE_ADMIN;
GRANT UNLIMITED TABLESPACE TO LIQUIBASE_ADMIN;
ALTER USER LIQUIBASE_ADMIN DEFAULT ROLE ALL;

--CREATE VANSOCSCAN
CREATE ROLE VANSOCSCAN_ROLE NOT IDENTIFIED;

EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_AUDIT_SESSION','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_DATA_FILES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_DB_LINKS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_ENCRYPTED_COLUMNS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_EXTERNAL_TABLES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_INDEXES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_LIBRARIES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_OBJECTS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_OBJ_AUDIT_OPTS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_PRIV_AUDIT_OPTS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_PROCEDURES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_PROFILES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_PROXIES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_REGISTRY','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_ROLES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_ROLE_PRIVS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_SEGMENTS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_SOURCE','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_STMT_AUDIT_OPTS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_SYS_PRIVS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_TABLES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_TABLESPACES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_TAB_PRIVS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_TS_QUOTAS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_USERS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_USERS_WITH_DEFPWD','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_VIEWS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('LINK$','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('PRODUCT_COMPONENT_VERSION','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('REGISTRY$HISTORY','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('USER$','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$DATABASE','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$DATAFILE','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$ENCRYPTED_TABLESPACES','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$INSTANCE','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$LOG','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$LOGFILE','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$PARAMETER','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$PWFILE_USERS','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$SESSION','VANSOCSCAN_ROLE','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBMS_FLASHBACK','VANSOCSCAN_ROLE','EXECUTE');

GRANT CREATE SESSION TO VANSOCSCAN_ROLE;

CREATE USER VANSOCSCAN IDENTIFIED BY "&4"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE APP_PROFILE
  ACCOUNT LOCK;

GRANT VANSOCSCAN_ROLE TO VANSOCSCAN;
ALTER USER VANSOCSCAN DEFAULT ROLE ALL;

COMMIT;
