EXEC RDSADMIN.RDSADMIN_UTIL.ALTER_SUPPLEMENTAL_LOGGING(P_ACTION => 'ADD');

CREATE ROLE REPLICATION_SOURCE_USER NOT IDENTIFIED;
GRANT CREATE SESSION TO REPLICATION_SOURCE_USER;
GRANT SELECT ANY TRANSACTION TO REPLICATION_SOURCE_USER;
GRANT LOGMINING TO REPLICATION_SOURCE_USER; 

EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_CATALOG', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_CONS_COLUMNS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_CONSTRAINTS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_ENCRYPTED_COLUMNS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_IND_COLUMNS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_INDEXES', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_LOG_GROUPS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_OBJECTS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_TAB_COLS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_TAB_PARTITIONS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_TABLES', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_USERS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ALL_VIEWS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_REGISTRY', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBA_TABLESPACES', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('DBMS_LOGMNR', 'REPLICATION_SOURCE_USER', 'EXECUTE');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('ENC$', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('OBJ$', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('REGISTRY$SQLPATCH', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$ARCHIVED_LOG', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$CONTAINERS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$DATABASE', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$INSTANCE', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$LOG', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$LOGFILE', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$LOGMNR_CONTENTS','REPLICATION_SOURCE_USER','SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$LOGMNR_LOGS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$NLS_PARAMETERS', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$PARAMETER', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$STANDBY_LOG', 'REPLICATION_SOURCE_USER', 'SELECT'); 
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$THREAD', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$TIMEZONE_NAMES', 'REPLICATION_SOURCE_USER', 'SELECT');
EXEC RDSADMIN.RDSADMIN_UTIL.GRANT_SYS_OBJECT('V_$TRANSACTION', 'REPLICATION_SOURCE_USER', 'SELECT');

EXEC RDSADMIN.RDSADMIN_UTIL.SET_CONFIGURATION('ARCHIVELOG RETENTION HOURS', 48);
COMMIT;

EXEC RDSADMIN.RDSADMIN_UTIL.SWITCH_LOGFILE;

CREATE USER "&1" IDENTIFIED BY "&2"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE APP_PROFILE
    ACCOUNT UNLOCK;

ALTER USER "&1" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO "&1";
GRANT REPLICATION_SOURCE_USER TO "&1";
