DROP ROLE LINKS_READONLY_ROLE;
DROP USER LINKS_RO CASCADE;

CREATE ROLE LINKS_READONLY_ROLE NOT IDENTIFIED;
GRANT CREATE SESSION TO LINKS_READONLY_ROLE;
GRANT SELECT ANY TABLE TO LINKS_READONLY_ROLE;

CREATE USER LINKS_RO IDENTIFIED BY "&1"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE APP_PROFILE
  ACCOUNT UNLOCK;

GRANT LINKS_READONLY_ROLE TO LINKS_RO;
ALTER USER LINKS_RO DEFAULT ROLE ALL;
