DECLARE
   CURSOR CURINDEX
   IS
      SELECT OWNER, INDEX_NAME
        FROM DBA_INDEXES
       WHERE STATUS = 'UNUSABLE';

   VC_OWNER        ALL_INDEXES.OWNER%TYPE;
   VC_INDEX_NAME   ALL_INDEXES.INDEX_NAME%TYPE;
BEGIN
   OPEN CURINDEX;

   LOOP
      FETCH CURINDEX INTO VC_OWNER, VC_INDEX_NAME;

      EXIT WHEN CURINDEX%NOTFOUND;

      EXECUTE IMMEDIATE
            'ALTER INDEX '
         || VC_OWNER
         || '.'
         || VC_INDEX_NAME
         || ' REBUILD ONLINE';
   END LOOP;

   CLOSE CURINDEX;
EXCEPTION
   WHEN OTHERS
   THEN
      IF (CURINDEX%ISOPEN)
      THEN
         CLOSE CURINDEX;
      END IF;
END;
/