CREATE ROLE &&ROLENAME NOT IDENTIFIED;
GRANT CREATE SESSION TO &&ROLENAME;

GRANT ALTER ANY PROCEDURE TO &&ROLENAME;
GRANT ALTER ANY SEQUENCE TO &&ROLENAME;
GRANT ALTER ANY TABLE TO &&ROLENAME;
GRANT CREATE ANY INDEX TO &&ROLENAME;
GRANT CREATE ANY PROCEDURE TO &&ROLENAME;
GRANT CREATE ANY SEQUENCE TO &&ROLENAME;
GRANT CREATE ANY TABLE TO &&ROLENAME;
GRANT CREATE ANY VIEW TO &&ROLENAME;
GRANT DELETE ANY TABLE TO &&ROLENAME;
GRANT DROP ANY INDEX TO &&ROLENAME;
GRANT DROP ANY PROCEDURE TO &&ROLENAME;
GRANT DROP ANY SEQUENCE TO &&ROLENAME;
GRANT DROP ANY TABLE TO &&ROLENAME;
GRANT DROP ANY VIEW TO &&ROLENAME;
GRANT INSERT ANY TABLE TO &&ROLENAME;
GRANT LOCK ANY TABLE TO &&ROLENAME;
GRANT SELECT ANY TABLE TO &&ROLENAME;
GRANT SELECT ANY TRANSACTION TO &&ROLENAME;
GRANT SELECT ON DBA_INDEXES TO &&ROLENAME;
GRANT SELECT ON DBA_OBJECTS TO &&ROLENAME;
GRANT SELECT ON DBA_SEQUENCES TO &&ROLENAME;
GRANT SELECT ON DBA_SYNONYMS TO &&ROLENAME;
GRANT SELECT ON DBA_TAB_PRIVS TO &&ROLENAME;
GRANT SELECT ON DBA_TABLES TO &&ROLENAME;
GRANT SELECT ON DBA_TRIGGERS TO &&ROLENAME;
GRANT SELECT ON DBA_TYPES TO &&ROLENAME;
GRANT SELECT ON DBA_USERS TO &&ROLENAME;
GRANT SELECT ON V$NLS_PARAMETERS TO &&ROLENAME;
GRANT SELECT ON V$TIMEZONE_NAMES TO &&ROLENAME;
GRANT UPDATE ANY TABLE TO &&ROLENAME;

EXEC RDSADMIN.RDSADMIN_UTIL.SET_CONFIGURATION('ARCHIVELOG RETENTION HOURS',48);

CREATE USER "&&USERNAME" IDENTIFIED BY "&PASSWORD"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE APP_PROFILE
    ACCOUNT UNLOCK;

ALTER USER "&&USERNAME" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO "&&USERNAME";
GRANT "&&ROLENAME" TO "&&USERNAME";