ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

CREATE ROLE &&ROLENAME NOT IDENTIFIED;
GRANT CREATE SESSION TO &&ROLENAME;
GRANT EXECUTE ON DBMS_LOGMNR TO &&ROLENAME;
GRANT LOGMINING TO &&ROLENAME; 

GRANT SELECT ANY TRANSACTION TO &&ROLENAME;
GRANT SELECT ON ALL_CATALOG TO &&ROLENAME;
GRANT SELECT ON ALL_CONS_COLUMNS TO &&ROLENAME;
GRANT SELECT ON ALL_CONSTRAINTS TO &&ROLENAME;
GRANT SELECT ON ALL_ENCRYPTED_COLUMNS TO &&ROLENAME;
GRANT SELECT ON ALL_IND_COLUMNS TO &&ROLENAME;
GRANT SELECT ON ALL_INDEXES TO &&ROLENAME;
GRANT SELECT ON ALL_LOG_GROUPS TO &&ROLENAME;
GRANT SELECT ON ALL_OBJECTS TO &&ROLENAME;
GRANT SELECT ON ALL_TAB_COLS TO &&ROLENAME;
GRANT SELECT ON ALL_TAB_PARTITIONS TO &&ROLENAME;
GRANT SELECT ON ALL_TABLES TO &&ROLENAME;
GRANT SELECT ON ALL_USERS TO &&ROLENAME;
GRANT SELECT ON DBA_TABLESPACES TO &&ROLENAME;
GRANT SELECT ON DBA_OBJECTS TO &&ROLENAME;
GRANT SELECT ON SYS.DBA_REGISTRY TO &&ROLENAME;
GRANT SELECT ON SYS.ENC$ TO &&ROLENAME;
GRANT SELECT ON SYS.OBJ$ TO &&ROLENAME;
GRANT SELECT ON V_$ARCHIVED_LOG TO &&ROLENAME;
GRANT SELECT ON V_$DATABASE TO &&ROLENAME;
GRANT SELECT ON V_$INSTANCE TO &&ROLENAME;
GRANT SELECT ON V_$LOG TO &&ROLENAME;
GRANT SELECT ON V_$LOGFILE TO &&ROLENAME;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO &&ROLENAME;
GRANT SELECT ON V_$LOGMNR_LOGS TO &&ROLENAME;
GRANT SELECT ON V_$NLS_PARAMETERS TO &&ROLENAME;
GRANT SELECT ON V_$PARAMETER TO &&ROLENAME;
GRANT SELECT ON V_$THREAD TO &&ROLENAME;
GRANT SELECT ON V_$TIMEZONE_NAMES TO &&ROLENAME;
GRANT SELECT ON V_$TRANSACTION TO &&ROLENAME;

CREATE USER "&&USERNAME" IDENTIFIED BY "&PASSWORD"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK;

ALTER USER "&&USERNAME" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO "&&USERNAME";
GRANT "&&ROLENAME" TO "&&USERNAME";

--GRANT SELECT ON &&SOURCE_OWNER.&&SOURCE_TABLE TO &&USERNAME;
--GRANT FLASHBACK ON &&SOURCE_OWNER.&&SOURCE_TABLE TO &&USERNAME;
--ALTER TABLE &&SOURCE_OWNER.&&SOURCE_TABLE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;