CREATE USER LIQUIBASE_ADMIN IDENTIFIED BY "&1"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE APP_PROFILE
  ACCOUNT UNLOCK;

GRANT LIQUIBASE_ADMIN_ROLE TO LIQUIBASE_ADMIN;
GRANT UNLIMITED TABLESPACE TO LIQUIBASE_ADMIN;
ALTER USER LIQUIBASE_ADMIN DEFAULT ROLE ALL;
